name: ${APP_NAME_HOST}

networks:
  internal:
    name: ${APP_NAME_HOST}_internal
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  habitat-config:
  authelia-secrets:
  authelia-data:
  lldap-data:


secrets:
  AUTHELIA_OIDC_HMAC_SECRET:
    file: ${SECRETS_DIR}/AUTHELIA_OIDC_HMAC_SECRET
  AUTHELIA_OIDC_JWKS_KEY_PRIVATE:
    file: ${SECRETS_DIR}/AUTHELIA_OIDC_JWKS_KEY_PRIVATE
  GRAFANA_OAUTH_CLIENT_ID:
    file: ${SECRETS_DIR}/GRAFANA_OAUTH_CLIENT_ID
  GRAFANA_OAUTH_CLIENT_SECRET_HASHED_PBKDF2:
    file: ${SECRETS_DIR}/GRAFANA_OAUTH_CLIENT_SECRET_HASHED_PBKDF2
  LLDAP_JWT_SECRET:
    file: ${SECRETS_DIR}/LLDAP_JWT_SECRET
  LLDAP_KEY_SEED:
    file: ${SECRETS_DIR}/LLDAP_KEY_SEED
  LLDAP_ADMIN_PASSWORD:
    file: ${SECRETS_DIR}/LLDAP_ADMIN_PASSWORD

services:

  habitat-config-scent:
    image: tschebbischeff/habitat-config:latest
    container_name: ${APP_NAME_HOST}_habitat-config-scent
    restart: no
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/habitat-config.env
        required: false
    environment:
      MODULE_NAME: "scent"
    networks:
      internal:
    volumes:
      - habitat-config:/habitat-config/orchestration
      - ./habitat-config:/habitat-config/source:ro

  authelia:
    build:
      context: ./authelia
    container_name: ${APP_NAME_HOST}_authelia
    restart: always
    expose:
      - "9091"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/authelia.env
        required: false
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: "/secrets/jwt"
      AUTHELIA_SESSION_SECRET_FILE: "/secrets/session"
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: "/secrets/storage_key"
      X_AUTHELIA_CONFIG_FILTERS: "template"
      X_AUTHELIA_HEALTHCHECK: "true"
      # LLDAP_LDAP_BASE_DN: "//** Generated from APP_HOST in entrypoint-hook.sh **//"
    secrets:
      - AUTHELIA_OIDC_HMAC_SECRET
      - AUTHELIA_OIDC_JWKS_KEY_PRIVATE
      - GRAFANA_OAUTH_CLIENT_ID
      - GRAFANA_OAUTH_CLIENT_SECRET_HASHED_PBKDF2
      - LLDAP_ADMIN_PASSWORD
    volumes:
      - ./authelia/config:/config:ro
      - authelia-secrets:/secrets
      - authelia-data:/data
    networks:
      internal:
    healthcheck:
      test: [ "CMD", "./healthcheck.sh" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      lldap:
        condition: service_healthy

  lldap:
    build:
      context: ./lldap
    container_name: ${APP_NAME_HOST}_lldap
    restart: always
    expose:
      - "3890"
      - "17170"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/lldap.env
        required: false
    environment:
      UID: "0"
      GID: "0"
      TZ: "${TIMEZONE}"
      LLDAP_JWT_SECRET_FILE: "/run/secrets/LLDAP_JWT_SECRET"
      LLDAP_KEY_SEED: "/run/secrets/LLDAP_KEY_SEED"
      LLDAP_KEY_FILE: ""
      LLDAP_LDAP_USER_DN: "admin"
      LLDAP_LDAP_USER_EMAIL: "admin@${APP_HOST}"
      LLDAP_LDAP_USER_PASS_FILE: "/run/secrets/LLDAP_ADMIN_PASSWORD"
      LLDAP_FORCE_LDAP_USER_PASS_RESET: "always"
      # LLDAP_LDAP_BASE_DN: "//** Generated from APP_HOST in entrypoint-hook.sh **//"
    secrets:
      - LLDAP_JWT_SECRET
      - LLDAP_KEY_SEED
      - LLDAP_ADMIN_PASSWORD
    volumes:
      - lldap-data:/data
      - ./lldap/bootstrap:/bootstrap:ro
    networks:
      internal:
    healthcheck:
      test: [ "CMD", "/app/lldap", "healthcheck", "--config-file", "/data/lldap_config.toml" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
