name: ${APP_NAME_HOST}

networks:
  internal:
    name: ${APP_NAME_HOST}_internal
    driver: bridge
    ipam:
      config:
        - subnet: "${APP_NETWORK_POOL}"

volumes:
  habitat-config:
  authelia-secrets:
  authelia-data:
  authelia-config:
  lldap-data:
  lldap-bootstrap:


secrets:
  AUTHELIA_OIDC_HMAC_SECRET:
    file: ${SECRETS_DIR}/AUTHELIA_OIDC_HMAC_SECRET
  AUTHELIA_OIDC_JWKS_KEY_PRIVATE:
    file: ${SECRETS_DIR}/AUTHELIA_OIDC_JWKS_KEY_PRIVATE
  LLDAP_JWT_SECRET:
    file: ${SECRETS_DIR}/LLDAP_JWT_SECRET
  LLDAP_KEY_SEED:
    file: ${SECRETS_DIR}/LLDAP_KEY_SEED
  LLDAP_ADMIN_PASSWORD:
    file: ${SECRETS_DIR}/LLDAP_ADMIN_PASSWORD

services:

  habitat-config-scent:
    image: tschebbischeff/habitat-config:latest
    container_name: ${APP_NAME_HOST}_habitat-config-scent
    restart: no
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/habitat-config.env
        required: false
    environment:
      MODULE_NAME: "scent"
    networks:
      internal:
    volumes:
      - habitat-config:/habitat-config/orchestration
      - ./habitat-config:/habitat-config/source:ro
      - lldap-bootstrap:/habitat-config/target/lldap
      - authelia-config:/habitat-config/target/authelia

  authelia:
    build:
      context: ./authelia
    container_name: ${APP_NAME_HOST}_authelia
    restart: unless-stopped
    expose:
      - "9091"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/authelia.env
        required: false
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: "/secrets/jwt"
      AUTHELIA_SESSION_SECRET_FILE: "/secrets/session"
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: "/secrets/storage_key"
      X_AUTHELIA_CONFIG_FILTERS: "template"
      X_AUTHELIA_HEALTHCHECK: "true"
      # LLDAP_LDAP_BASE_DN: "//** Generated from APP_HOST in entrypoint-hook.sh **//"
    secrets:
      - AUTHELIA_OIDC_HMAC_SECRET
      - AUTHELIA_OIDC_JWKS_KEY_PRIVATE
      - LLDAP_ADMIN_PASSWORD
    volumes:
      - authelia-config:/config:ro
      - authelia-secrets:/secrets
      - authelia-data:/data
      - ${VOLUME_DIR}/authelia-backups:/backups
    networks:
      internal:
    healthcheck:
      test: [ "CMD", "./healthcheck.sh" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      lldap:
        condition: service_healthy

  lldap:
    build:
      context: ./lldap
    container_name: ${APP_NAME_HOST}_lldap
    restart: unless-stopped
    expose:
      - "3890"
      - "17170"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/lldap.env
        required: false
    environment:
      UID: "0"
      GID: "0"
      LLDAP_JWT_SECRET_FILE: "/run/secrets/LLDAP_JWT_SECRET"
      LLDAP_KEY_SEED: "/run/secrets/LLDAP_KEY_SEED"
      LLDAP_KEY_FILE: ""
      LLDAP_LDAP_USER_DN: "admin"
      LLDAP_LDAP_USER_EMAIL: "admin@${APP_HOST}"
      LLDAP_LDAP_USER_PASS_FILE: "/run/secrets/LLDAP_ADMIN_PASSWORD"
      LLDAP_FORCE_LDAP_USER_PASS_RESET: "always"
      # LLDAP_LDAP_BASE_DN: "//** Generated from APP_HOST in entrypoint-hook.sh **//"
    secrets:
      - LLDAP_JWT_SECRET
      - LLDAP_KEY_SEED
      - LLDAP_ADMIN_PASSWORD
    volumes:
      - lldap-data:/data
      - lldap-bootstrap:/bootstrap:ro
      - ${VOLUME_DIR}/lldap-backups:/backups
    networks:
      internal:
    healthcheck:
      # This healthcheck prints a lot of connection logs
      test: [ "CMD", "/app/lldap", "healthcheck", "--config-file", "/data/lldap_config.toml" ]
      # This healthchecks only checks the API connection and is less accurate
      # test: [ "CMD-SHELL", "curl -so /dev/null -w '%{http_code}' 'http://127.0.0.1:17170/health' | grep -q '^200$' || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      habitat-config-scent:
        condition: service_completed_successfully
