http:
  middlewares:
    auth-proxy:
      forwardAuth:
        address: 'http://{{ env "APP_NAME_HOST" }}_authelia:9091/api/authz/forward-auth'
        trustForwardHeader: true
        maxResponseBodySize: 1048576 # 1MiB
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Name"
          - "Remote-Email"
