server:
  address: 'tcp://:9091/'
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'

log:
  level: info

session:
  name: authelia_session
  same_site: lax
  expiration: 1h
  inactivity: 5m
  cookies:
    - domain: '{{ env "APP_HOST" }}'
      authelia_url: 'https://authelia.{{ env "APP_HOST" }}'

authentication_backend:
  ldap:
    implementation: 'lldap'
    address: 'ldap://{{ env "APP_NAME_HOST" }}_lldap:3890'
    base_dn: '{{ env "LLDAP_LDAP_BASE_DN" }}'
    user: 'UID=admin,OU=people,{{ env "LLDAP_LDAP_BASE_DN" }}'
    password: '{{ secret "/run/secrets/LLDAP_ADMIN_PASSWORD" }}'
#   file:
#     path: /config/users.yml

storage:
  local:
    path: /data/db.sqlite3

notifier:
  filesystem:
    filename: /data/notification.txt

access_control:
  default_policy: deny
  rules:
    - domain: 'authelia.{{ env "APP_HOST" }}'
      policy: bypass
    - domain: 'lldap.{{ env "APP_HOST" }}'
      policy: bypass
    - domain: '*.{{ env "APP_HOST" }}'
      subject: 'group:admins'
      policy: one_factor

identity_providers:
  oidc: # https://www.authelia.com/integration/openid-connect/frequently-asked-questions/#how-do-i-generate-a-client-identifier-or-client-secret
    hmac_secret: '{{ secret "/run/secrets/AUTHELIA_OIDC_HMAC_SECRET" }}' # docker run --rm authelia/authelia:latest authelia crypto rand --length 64 --charset alphanumeric
    jwks: # docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd)":/keys authelia/authelia:latest authelia crypto pair rsa generate --directory /keys
      - key: |
          {{ secret "/run/secrets/AUTHELIA_OIDC_JWKS_KEY_PRIVATE" | indent 10 | trimPrefix "          " }}
        algorithm: 'RS256'
        use: 'sig'
    clients:
      - client_id: 'stub_client'
        client_name: 'Stub Client'
        client_secret: '$pbkdf2-sha512$310000$xLaEduCvJub4g1QEiafUAQ$HkpVyPR7dsyUL4FWU75KAD1JD94fTf54zI9TKR6sqf.lOqPcEx5NtTlZ9L/FwslrL7J3v9xzA6mHqt/8NJ/jvw'
        public: false
        authorization_policy: 'one_factor'
        redirect_uris:
          - 'https://lldap.{{ env "APP_HOST" }}'
        scopes:
          - 'openid'
